//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="http://tempuri.org/")]
public partial class CEAWebService : System.Web.Services.Protocols.SoapHttpClientProtocol
{
    
    private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetUserListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetCurriculumListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetClassListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetClassRoomListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetClassStudentMapListOperationCompleted;
    
    private System.Threading.SendOrPostCallback GetArrangeClassListOperationCompleted;
    
    /// <remarks/>
    public CEAWebService()
    {
        this.Url = System.Configuration.ConfigurationSettings.AppSettings["CEAWebServiceUrl"].ToString();
    }
    
    /// <remarks/>
    public event HelloWorldCompletedEventHandler HelloWorldCompleted;
    
    /// <remarks/>
    public event GetUserListCompletedEventHandler GetUserListCompleted;
    
    /// <remarks/>
    public event GetCurriculumListCompletedEventHandler GetCurriculumListCompleted;
    
    /// <remarks/>
    public event GetClassListCompletedEventHandler GetClassListCompleted;
    
    /// <remarks/>
    public event GetClassRoomListCompletedEventHandler GetClassRoomListCompleted;
    
    /// <remarks/>
    public event GetClassStudentMapListCompletedEventHandler GetClassStudentMapListCompleted;
    
    /// <remarks/>
    public event GetArrangeClassListCompletedEventHandler GetArrangeClassListCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string HelloWorld()
    {
        object[] results = this.Invoke("HelloWorld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void HelloWorldAsync()
    {
        this.HelloWorldAsync(null);
    }
    
    /// <remarks/>
    public void HelloWorldAsync(object userState)
    {
        if ((this.HelloWorldOperationCompleted == null))
        {
            this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
        }
        this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
    }
    
    private void OnHelloWorldOperationCompleted(object arg)
    {
        if ((this.HelloWorldCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUserList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CEAUserInfoEntity[] GetUserList()
    {
        object[] results = this.Invoke("GetUserList", new object[0]);
        return ((CEAUserInfoEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetUserListAsync()
    {
        this.GetUserListAsync(null);
    }
    
    /// <remarks/>
    public void GetUserListAsync(object userState)
    {
        if ((this.GetUserListOperationCompleted == null))
        {
            this.GetUserListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUserListOperationCompleted);
        }
        this.InvokeAsync("GetUserList", new object[0], this.GetUserListOperationCompleted, userState);
    }
    
    private void OnGetUserListOperationCompleted(object arg)
    {
        if ((this.GetUserListCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetUserListCompleted(this, new GetUserListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCurriculumList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CEACurriculumInfoEntity[] GetCurriculumList()
    {
        object[] results = this.Invoke("GetCurriculumList", new object[0]);
        return ((CEACurriculumInfoEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetCurriculumListAsync()
    {
        this.GetCurriculumListAsync(null);
    }
    
    /// <remarks/>
    public void GetCurriculumListAsync(object userState)
    {
        if ((this.GetCurriculumListOperationCompleted == null))
        {
            this.GetCurriculumListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCurriculumListOperationCompleted);
        }
        this.InvokeAsync("GetCurriculumList", new object[0], this.GetCurriculumListOperationCompleted, userState);
    }
    
    private void OnGetCurriculumListOperationCompleted(object arg)
    {
        if ((this.GetCurriculumListCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetCurriculumListCompleted(this, new GetCurriculumListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClassList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CEAClassInfoEntity[] GetClassList()
    {
        object[] results = this.Invoke("GetClassList", new object[0]);
        return ((CEAClassInfoEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetClassListAsync()
    {
        this.GetClassListAsync(null);
    }
    
    /// <remarks/>
    public void GetClassListAsync(object userState)
    {
        if ((this.GetClassListOperationCompleted == null))
        {
            this.GetClassListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassListOperationCompleted);
        }
        this.InvokeAsync("GetClassList", new object[0], this.GetClassListOperationCompleted, userState);
    }
    
    private void OnGetClassListOperationCompleted(object arg)
    {
        if ((this.GetClassListCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetClassListCompleted(this, new GetClassListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClassRoomList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CEAClassRoomInfoEntity[] GetClassRoomList()
    {
        object[] results = this.Invoke("GetClassRoomList", new object[0]);
        return ((CEAClassRoomInfoEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetClassRoomListAsync()
    {
        this.GetClassRoomListAsync(null);
    }
    
    /// <remarks/>
    public void GetClassRoomListAsync(object userState)
    {
        if ((this.GetClassRoomListOperationCompleted == null))
        {
            this.GetClassRoomListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassRoomListOperationCompleted);
        }
        this.InvokeAsync("GetClassRoomList", new object[0], this.GetClassRoomListOperationCompleted, userState);
    }
    
    private void OnGetClassRoomListOperationCompleted(object arg)
    {
        if ((this.GetClassRoomListCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetClassRoomListCompleted(this, new GetClassRoomListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetClassStudentMapList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CEAClassStudentMapEntity[] GetClassStudentMapList()
    {
        object[] results = this.Invoke("GetClassStudentMapList", new object[0]);
        return ((CEAClassStudentMapEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetClassStudentMapListAsync()
    {
        this.GetClassStudentMapListAsync(null);
    }
    
    /// <remarks/>
    public void GetClassStudentMapListAsync(object userState)
    {
        if ((this.GetClassStudentMapListOperationCompleted == null))
        {
            this.GetClassStudentMapListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassStudentMapListOperationCompleted);
        }
        this.InvokeAsync("GetClassStudentMapList", new object[0], this.GetClassStudentMapListOperationCompleted, userState);
    }
    
    private void OnGetClassStudentMapListOperationCompleted(object arg)
    {
        if ((this.GetClassStudentMapListCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetClassStudentMapListCompleted(this, new GetClassStudentMapListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetArrangeClassList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public CEAArrangeClassEntity[] GetArrangeClassList()
    {
        object[] results = this.Invoke("GetArrangeClassList", new object[0]);
        return ((CEAArrangeClassEntity[])(results[0]));
    }
    
    /// <remarks/>
    public void GetArrangeClassListAsync()
    {
        this.GetArrangeClassListAsync(null);
    }
    
    /// <remarks/>
    public void GetArrangeClassListAsync(object userState)
    {
        if ((this.GetArrangeClassListOperationCompleted == null))
        {
            this.GetArrangeClassListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrangeClassListOperationCompleted);
        }
        this.InvokeAsync("GetArrangeClassList", new object[0], this.GetArrangeClassListOperationCompleted, userState);
    }
    
    private void OnGetArrangeClassListOperationCompleted(object arg)
    {
        if ((this.GetArrangeClassListCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.GetArrangeClassListCompleted(this, new GetArrangeClassListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CEAUserInfoEntity
{
    
    private string[] errorListField;
    
    private int idField;
    
    private string codeField;
    
    private string nameField;
    
    private string passwordField;
    
    private string typeField;
    
    private string groupField;
    
    private string companyField;
    
    private string departmentField;
    
    private string positionIDField;
    
    private string positionNameField;
    
    private string sexField;
    
    private System.Nullable<System.DateTime> birthdayField;
    
    private string emailField;
    
    private string phoneField;
    
    private string addressField;

    private string identityCardField;
    
    private string validField;
    
    private System.DateTime createTimeField;
    
    private string createByField;
    
    private System.DateTime updateTimeField;
    
    private string updateByField;
    
    /// <remarks/>
    public string[] ErrorList
    {
        get
        {
            return this.errorListField;
        }
        set
        {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Password
    {
        get
        {
            return this.passwordField;
        }
        set
        {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    public string Group
    {
        get
        {
            return this.groupField;
        }
        set
        {
            this.groupField = value;
        }
    }
    
    /// <remarks/>
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    public string Department
    {
        get
        {
            return this.departmentField;
        }
        set
        {
            this.departmentField = value;
        }
    }
    
    /// <remarks/>
    public string PositionID
    {
        get
        {
            return this.positionIDField;
        }
        set
        {
            this.positionIDField = value;
        }
    }
    
    /// <remarks/>
    public string PositionName
    {
        get
        {
            return this.positionNameField;
        }
        set
        {
            this.positionNameField = value;
        }
    }
    
    /// <remarks/>
    public string Sex
    {
        get
        {
            return this.sexField;
        }
        set
        {
            this.sexField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> Birthday
    {
        get
        {
            return this.birthdayField;
        }
        set
        {
            this.birthdayField = value;
        }
    }
    
    /// <remarks/>
    public string Email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string Phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }
    
    /// <remarks/>
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    public string IdentityCard
    {
        get
        {
            return this.identityCardField;
        }
        set
        {
            this.identityCardField = value;
        }
    }
    
    
    /// <remarks/>
    public string Valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    public string CreateBy
    {
        get
        {
            return this.createByField;
        }
        set
        {
            this.createByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateBy
    {
        get
        {
            return this.updateByField;
        }
        set
        {
            this.updateByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CEAArrangeClassEntity
{
    
    private string[] errorListField;
    
    private int idField;
    
    private string curriculumCodeField;
    
    private string classCodeField;
    
    private string classRoomCodeField;
    
    private string teacherCodeField;
    
    private System.Nullable<System.DateTime> startTimeField;
    
    private System.Nullable<System.DateTime> endTimeField;
    
    private string remarkField;
    
    private System.Nullable<int> bespeakCountField;
    
    private System.Nullable<int> attendCountField;
    
    private System.Nullable<int> passedCountField;
    
    private string validField;
    
    private System.DateTime createTimeField;
    
    private string createByField;
    
    private System.DateTime updateTimeField;
    
    private string updateByField;
    
    /// <remarks/>
    public string[] ErrorList
    {
        get
        {
            return this.errorListField;
        }
        set
        {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string CurriculumCode
    {
        get
        {
            return this.curriculumCodeField;
        }
        set
        {
            this.curriculumCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ClassCode
    {
        get
        {
            return this.classCodeField;
        }
        set
        {
            this.classCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ClassRoomCode
    {
        get
        {
            return this.classRoomCodeField;
        }
        set
        {
            this.classRoomCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TeacherCode
    {
        get
        {
            return this.teacherCodeField;
        }
        set
        {
            this.teacherCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> EndTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public string Remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> BespeakCount
    {
        get
        {
            return this.bespeakCountField;
        }
        set
        {
            this.bespeakCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> AttendCount
    {
        get
        {
            return this.attendCountField;
        }
        set
        {
            this.attendCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> PassedCount
    {
        get
        {
            return this.passedCountField;
        }
        set
        {
            this.passedCountField = value;
        }
    }
    
    /// <remarks/>
    public string Valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    public string CreateBy
    {
        get
        {
            return this.createByField;
        }
        set
        {
            this.createByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateBy
    {
        get
        {
            return this.updateByField;
        }
        set
        {
            this.updateByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CEAClassStudentMapEntity
{
    
    private string[] errorListField;
    
    private int idField;
    
    private string classCodeField;
    
    private string studentCodeField;
    
    private string validField;
    
    private System.DateTime createTimeField;
    
    private string createByField;
    
    private System.DateTime updateTimeField;
    
    private string updateByField;
    
    /// <remarks/>
    public string[] ErrorList
    {
        get
        {
            return this.errorListField;
        }
        set
        {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string ClassCode
    {
        get
        {
            return this.classCodeField;
        }
        set
        {
            this.classCodeField = value;
        }
    }
    
    /// <remarks/>
    public string StudentCode
    {
        get
        {
            return this.studentCodeField;
        }
        set
        {
            this.studentCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    public string CreateBy
    {
        get
        {
            return this.createByField;
        }
        set
        {
            this.createByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateBy
    {
        get
        {
            return this.updateByField;
        }
        set
        {
            this.updateByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CEAClassRoomInfoEntity
{
    
    private string[] errorListField;
    
    private int classRoomIDField;
    
    private string codeField;
    
    private string nameField;
    
    private string addressField;
    
    private string typeField;
    
    private System.Nullable<int> seatNumField;
    
    private string remarkField;
    
    private string validField;
    
    private System.DateTime createTimeField;
    
    private string createByField;
    
    private System.DateTime updateTimeField;
    
    private string updateByField;
    
    /// <remarks/>
    public string[] ErrorList
    {
        get
        {
            return this.errorListField;
        }
        set
        {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public int ClassRoomID
    {
        get
        {
            return this.classRoomIDField;
        }
        set
        {
            this.classRoomIDField = value;
        }
    }
    
    /// <remarks/>
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> SeatNum
    {
        get
        {
            return this.seatNumField;
        }
        set
        {
            this.seatNumField = value;
        }
    }
    
    /// <remarks/>
    public string Remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
    
    /// <remarks/>
    public string Valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    public string CreateBy
    {
        get
        {
            return this.createByField;
        }
        set
        {
            this.createByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateBy
    {
        get
        {
            return this.updateByField;
        }
        set
        {
            this.updateByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CEAClassInfoEntity
{
    
    private string[] errorListField;
    
    private int classIDField;
    
    private string codeField;
    
    private string nameField;
    
    private string typeField;
    
    private System.Nullable<System.DateTime> startTimeField;
    
    private System.Nullable<System.DateTime> endTimeField;
    
    private string teacherCodeField;
    
    private string companyField;
    
    private string departmentField;
    
    private string remarkField;
    
    private string validField;
    
    private System.DateTime createTimeField;
    
    private string createByField;
    
    private System.DateTime updateTimeField;
    
    private string updateByField;
    
    /// <remarks/>
    public string[] ErrorList
    {
        get
        {
            return this.errorListField;
        }
        set
        {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public int ClassID
    {
        get
        {
            return this.classIDField;
        }
        set
        {
            this.classIDField = value;
        }
    }
    
    /// <remarks/>
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> EndTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public string TeacherCode
    {
        get
        {
            return this.teacherCodeField;
        }
        set
        {
            this.teacherCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Company
    {
        get
        {
            return this.companyField;
        }
        set
        {
            this.companyField = value;
        }
    }
    
    /// <remarks/>
    public string Department
    {
        get
        {
            return this.departmentField;
        }
        set
        {
            this.departmentField = value;
        }
    }
    
    /// <remarks/>
    public string Remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
    
    /// <remarks/>
    public string Valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    public string CreateBy
    {
        get
        {
            return this.createByField;
        }
        set
        {
            this.createByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateBy
    {
        get
        {
            return this.updateByField;
        }
        set
        {
            this.updateByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
public partial class CEACurriculumInfoEntity
{
    
    private string[] errorListField;
    
    private int curriculumIDField;
    
    private string codeField;
    
    private string nameField;
    
    private string typeField;
    
    private System.Nullable<int> scoreField;
    
    private System.Nullable<System.DateTime> startTimeField;
    
    private System.Nullable<System.DateTime> endTimeField;
    
    private string remarkField;
    
    private string validField;
    
    private System.DateTime createTimeField;
    
    private string createByField;
    
    private System.DateTime updateTimeField;
    
    private string updateByField;
    
    /// <remarks/>
    public string[] ErrorList
    {
        get
        {
            return this.errorListField;
        }
        set
        {
            this.errorListField = value;
        }
    }
    
    /// <remarks/>
    public int CurriculumID
    {
        get
        {
            return this.curriculumIDField;
        }
        set
        {
            this.curriculumIDField = value;
        }
    }
    
    /// <remarks/>
    public string Code
    {
        get
        {
            return this.codeField;
        }
        set
        {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> Score
    {
        get
        {
            return this.scoreField;
        }
        set
        {
            this.scoreField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> StartTime
    {
        get
        {
            return this.startTimeField;
        }
        set
        {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> EndTime
    {
        get
        {
            return this.endTimeField;
        }
        set
        {
            this.endTimeField = value;
        }
    }
    
    /// <remarks/>
    public string Remark
    {
        get
        {
            return this.remarkField;
        }
        set
        {
            this.remarkField = value;
        }
    }
    
    /// <remarks/>
    public string Valid
    {
        get
        {
            return this.validField;
        }
        set
        {
            this.validField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateTime
    {
        get
        {
            return this.createTimeField;
        }
        set
        {
            this.createTimeField = value;
        }
    }
    
    /// <remarks/>
    public string CreateBy
    {
        get
        {
            return this.createByField;
        }
        set
        {
            this.createByField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime UpdateTime
    {
        get
        {
            return this.updateTimeField;
        }
        set
        {
            this.updateTimeField = value;
        }
    }
    
    /// <remarks/>
    public string UpdateBy
    {
        get
        {
            return this.updateByField;
        }
        set
        {
            this.updateByField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void GetUserListCompletedEventHandler(object sender, GetUserListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetUserListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal GetUserListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public CEAUserInfoEntity[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CEAUserInfoEntity[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void GetCurriculumListCompletedEventHandler(object sender, GetCurriculumListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetCurriculumListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal GetCurriculumListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public CEACurriculumInfoEntity[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CEACurriculumInfoEntity[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void GetClassListCompletedEventHandler(object sender, GetClassListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetClassListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal GetClassListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public CEAClassInfoEntity[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CEAClassInfoEntity[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void GetClassRoomListCompletedEventHandler(object sender, GetClassRoomListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetClassRoomListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal GetClassRoomListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public CEAClassRoomInfoEntity[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CEAClassRoomInfoEntity[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void GetClassStudentMapListCompletedEventHandler(object sender, GetClassStudentMapListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetClassStudentMapListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal GetClassStudentMapListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public CEAClassStudentMapEntity[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CEAClassStudentMapEntity[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
public delegate void GetArrangeClassListCompletedEventHandler(object sender, GetArrangeClassListCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("WindowsFormsApplication1", "1.0.0.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class GetArrangeClassListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    internal GetArrangeClassListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    /// <remarks/>
    public CEAArrangeClassEntity[] Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((CEAArrangeClassEntity[])(this.results[0]));
        }
    }
}
